#!/usr/bin/python


from git import GitError
from git import reset_initialization

try:
    success_msg = reset_initialization()
    print(success_msg)

except GitError as ex:
    exit(ex.value)
